<?php

namespace ContainerOEaJIWa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gh7VYy1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gh7VYy1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gh7VYy1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PinsController::delete' => ['privates', '.service_locator.bSMTVI5', 'get_ServiceLocator_BSMTVI5Service', true],
            'App\\Controller\\PinsController::edit' => ['privates', '.service_locator.Tpkrt51', 'get_ServiceLocator_Tpkrt51Service', true],
            'App\\Controller\\PinsController::index' => ['privates', '.service_locator.gKAdTWT', 'get_ServiceLocator_GKAdTWTService', true],
            'App\\Controller\\PinsController::show' => ['privates', '.service_locator.Tpkrt51', 'get_ServiceLocator_Tpkrt51Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.ztkjRWS', 'get_ServiceLocator_ZtkjRWSService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\PinsController:delete' => ['privates', '.service_locator.bSMTVI5', 'get_ServiceLocator_BSMTVI5Service', true],
            'App\\Controller\\PinsController:edit' => ['privates', '.service_locator.Tpkrt51', 'get_ServiceLocator_Tpkrt51Service', true],
            'App\\Controller\\PinsController:index' => ['privates', '.service_locator.gKAdTWT', 'get_ServiceLocator_GKAdTWTService', true],
            'App\\Controller\\PinsController:show' => ['privates', '.service_locator.Tpkrt51', 'get_ServiceLocator_Tpkrt51Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.ztkjRWS', 'get_ServiceLocator_ZtkjRWSService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.A0rcl1e', 'get_ServiceLocator_A0rcl1eService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\PinsController::delete' => '?',
            'App\\Controller\\PinsController::edit' => '?',
            'App\\Controller\\PinsController::index' => '?',
            'App\\Controller\\PinsController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PinsController:delete' => '?',
            'App\\Controller\\PinsController:edit' => '?',
            'App\\Controller\\PinsController:index' => '?',
            'App\\Controller\\PinsController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
