<?php

namespace ContainerOEaJIWa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Controller_ConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'liip_imagine.controller.config' shared service.
     *
     * @return \Liip\ImagineBundle\Config\Controller\ControllerConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'liip'.\DIRECTORY_SEPARATOR.'imagine-bundle'.\DIRECTORY_SEPARATOR.'Config'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ControllerConfig.php';

        return $container->privates['liip_imagine.controller.config'] = new \Liip\ImagineBundle\Config\Controller\ControllerConfig(301);
    }
}
