<?php

namespace ContainerOEaJIWa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonycasts_ResetPassword_TokenGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'symfonycasts.reset_password.token_generator' shared service.
     *
     * @return \SymfonyCasts\Bundle\ResetPassword\Generator\ResetPasswordTokenGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfonycasts'.\DIRECTORY_SEPARATOR.'reset-password-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Generator'.\DIRECTORY_SEPARATOR.'ResetPasswordTokenGenerator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfonycasts'.\DIRECTORY_SEPARATOR.'reset-password-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Generator'.\DIRECTORY_SEPARATOR.'ResetPasswordRandomGenerator.php';

        return $container->privates['symfonycasts.reset_password.token_generator'] = new \SymfonyCasts\Bundle\ResetPassword\Generator\ResetPasswordTokenGenerator($container->getEnv('APP_SECRET'), ($container->privates['symfonycasts.reset_password.random_generator'] ?? ($container->privates['symfonycasts.reset_password.random_generator'] = new \SymfonyCasts\Bundle\ResetPassword\Generator\ResetPasswordRandomGenerator())));
    }
}
