<?php

namespace Container0ceS68j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BSMTVI5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bSMTVI5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bSMTVI5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pin' => ['privates', '.errored..service_locator.bSMTVI5.App\\Entity\\Pin', NULL, 'Cannot autowire service ".service_locator.bSMTVI5": it references class "App\\Entity\\Pin" but no such service exists.'],
        ], [
            'em' => '?',
            'pin' => 'App\\Entity\\Pin',
        ]);
    }
}
