<?php

namespace Container0ceS68j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Tpkrt51.App\Entity\Pin' shared service.
     *
     * @return \App\Entity\Pin
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Tpkrt51": it references class "App\\Entity\\Pin" but no such service exists.');
    }
}
