<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOEaJIWa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOEaJIWa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOEaJIWa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOEaJIWa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOEaJIWa\App_KernelDevDebugContainer([
    'container.build_hash' => 'OEaJIWa',
    'container.build_id' => '1840015b',
    'container.build_time' => 1606918821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOEaJIWa');
