<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOO4RaL2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOO4RaL2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOO4RaL2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOO4RaL2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOO4RaL2\App_KernelDevDebugContainer([
    'container.build_hash' => 'OO4RaL2',
    'container.build_id' => '1f9c9c19',
    'container.build_time' => 1611762255,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOO4RaL2');
