<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKcVHlo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKcVHlo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCKcVHlo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCKcVHlo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCKcVHlo\App_KernelDevDebugContainer([
    'container.build_hash' => 'CKcVHlo',
    'container.build_id' => 'bda89046',
    'container.build_time' => 1611838284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKcVHlo');
