<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.d94b3b43.js',
                '/build/0.0317c458.js',
                '/build/app.c2507936.js',
            ],
            'css' => [
                '/build/app.9e32f08e.css',
            ],
        ],
    ],
],

]];
