<?php

namespace ContainerML1re1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GKAdTWTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gKAdTWT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gKAdTWT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pinRepository' => ['privates', 'App\\Repository\\PinRepository', 'getPinRepositoryService', true],
        ], [
            'pinRepository' => 'App\\Repository\\PinRepository',
        ]);
    }
}
