<?php

namespace ContainerML1re1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tpkrt51Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tpkrt51' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tpkrt51'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pin' => ['privates', '.errored..service_locator.Tpkrt51.App\\Entity\\Pin', NULL, 'Cannot autowire service ".service_locator.Tpkrt51": it references class "App\\Entity\\Pin" but no such service exists.'],
        ], [
            'pin' => 'App\\Entity\\Pin',
        ]);
    }
}
