<?php

namespace ContainerML1re1N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonycasts_VerifyEmail_QueryUtilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'symfonycasts.verify_email.query_utility' shared service.
     *
     * @return \SymfonyCasts\Bundle\VerifyEmail\Util\VerifyEmailQueryUtility
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfonycasts'.\DIRECTORY_SEPARATOR.'verify-email-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'VerifyEmailQueryUtility.php';

        return $container->privates['symfonycasts.verify_email.query_utility'] = new \SymfonyCasts\Bundle\VerifyEmail\Util\VerifyEmailQueryUtility();
    }
}
